# Generated by Django 5.2.8 on 2025-12-05 03:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_options_user_users_email_4b85f2_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeltaEarningRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Rule name (e.g., 'correct_answer', 'complete_practice')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(help_text="Description of earning rule")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Delta amount to award",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional conditions for earning (e.g., minimum accuracy)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delta Earning Rule",
                "verbose_name_plural": "Delta Earning Rules",
                "db_table": "delta_earning_rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeltaProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                ("description", models.TextField(help_text="Product description")),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature"),
                            ("content", "Content"),
                            ("badge", "Badge"),
                            ("boost", "Boost"),
                            ("cosmetic", "Cosmetic"),
                            ("other", "Other"),
                        ],
                        help_text="Type of product",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Delta coins",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Whether product is available for purchase"
                    ),
                ),
                (
                    "is_limited",
                    models.BooleanField(
                        default=False, help_text="Whether product has limited quantity"
                    ),
                ),
                (
                    "quantity_available",
                    models.IntegerField(
                        blank=True, help_text="Available quantity (for limited products)", null=True
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-star", help_text="Font Awesome icon class", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional product data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delta Product",
                "verbose_name_plural": "Delta Products",
                "db_table": "delta_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeltaWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique wallet identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current Delta balance (cannot be negative)",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total Deltas earned lifetime",
                        max_digits=20,
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total Deltas spent lifetime",
                        max_digits=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether wallet is active"),
                ),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False, help_text="If true, no transactions allowed (for security)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Wallet creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update timestamp"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Wallet owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delta_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delta Wallet",
                "verbose_name_plural": "Delta Wallets",
                "db_table": "delta_wallets",
            },
        ),
        migrations.CreateModel(
            name="DeltaTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique transaction identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earn"),
                            ("spend", "Spend"),
                            ("transfer", "Transfer"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus"),
                            ("admin_add", "Admin Add"),
                            ("admin_deduct", "Admin Deduct"),
                            ("reversal", "Reversal"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance before transaction",
                        max_digits=20,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance after transaction",
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="completed",
                        help_text="Transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External reference ID (e.g., practice session ID, purchase ID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of reference (e.g., 'practice_session', 'store_purchase')",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="Transaction description")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional transaction metadata"
                    ),
                ),
                (
                    "is_reversed",
                    models.BooleanField(
                        default=False, help_text="Whether this transaction has been reversed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Transaction timestamp"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this transaction (for admin actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delta_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related user (for transfers)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delta_related_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reversal transaction reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_transaction",
                        to="core.deltatransaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet involved in transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.deltawallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delta Transaction",
                "verbose_name_plural": "Delta Transactions",
                "db_table": "delta_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeltaPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether purchase is active/valid"),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="core.deltaproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delta_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="Associated Delta transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase",
                        to="core.deltatransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delta Purchase",
                "verbose_name_plural": "Delta Purchases",
                "db_table": "delta_purchases",
                "ordering": ["-purchased_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-purchased_at"], name="delta_purch_user_id_8c1586_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="deltawallet",
            index=models.Index(fields=["user"], name="delta_walle_user_id_1f861d_idx"),
        ),
        migrations.AddIndex(
            model_name="deltawallet",
            index=models.Index(fields=["created_at"], name="delta_walle_created_7173c0_idx"),
        ),
        migrations.AddIndex(
            model_name="deltatransaction",
            index=models.Index(
                fields=["wallet", "-created_at"], name="delta_trans_wallet__97b9bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deltatransaction",
            index=models.Index(
                fields=["transaction_type", "-created_at"], name="delta_trans_transac_754610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deltatransaction",
            index=models.Index(
                fields=["reference_id", "reference_type"], name="delta_trans_referen_035232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deltatransaction",
            index=models.Index(
                fields=["status", "-created_at"], name="delta_trans_status_d36ff0_idx"
            ),
        ),
    ]
