# Generated by Django 5.2.8 on 2025-12-08 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delta_coin_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Permission name (e.g., 'view_practice', 'manage_users')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="Unique code for this permission", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this permission allows"),
                ),
                (
                    "min_role_weight",
                    models.IntegerField(
                        default=1, help_text="Minimum role weight required to access this feature"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Permission category (e.g., 'practice', 'admin', 'content')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this permission is currently enforced"
                    ),
                ),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
                "db_table": "permissions",
                "ordering": ["category", "min_role_weight", "name"],
                "indexes": [
                    models.Index(fields=["codename"], name="permissions_codenam_5f0327_idx"),
                    models.Index(fields=["min_role_weight"], name="permissions_min_rol_63eb0a_idx"),
                    models.Index(fields=["category"], name="permissions_categor_b3ddb9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., User, Instructor, Admin)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        help_text="Role weight - higher number = more access", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this role can do"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this role is currently active"
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "db_table": "roles",
                "ordering": ["-weight"],
                "indexes": [
                    models.Index(fields=["weight"], name="roles_weight_fd5d41_idx"),
                    models.Index(fields=["name"], name="roles_name_a96913_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="User's role in the system",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.role",
            ),
        ),
    ]
