# Generated by Django 5.2.8 on 2025-12-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_permission_role_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.AlterField(
            model_name="role",
            name="weight",
            field=models.IntegerField(
                help_text="Role weight - higher number = more access (adjustable)", unique=True
            ),
        ),
    ]
