# Generated by Django 5.2.8 on 2025-12-01 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier_id",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable identifier (e.g., 'JKZRJ')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "question_id",
                    models.UUIDField(db_index=True, help_text="UUID from original source"),
                ),
                (
                    "domain_name",
                    models.CharField(
                        db_index=True,
                        help_text="Domain name (e.g., 'Craft and Structure')",
                        max_length=200,
                    ),
                ),
                (
                    "domain_code",
                    models.CharField(
                        db_index=True, help_text="Domain code (e.g., 'CAS')", max_length=20
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        help_text="Skill name (e.g., 'Cross-Text Connections')", max_length=200
                    ),
                ),
                (
                    "skill_code",
                    models.CharField(
                        db_index=True, help_text="Skill code (e.g., 'CTC')", max_length=20
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        default="College Board", help_text="Provider name", max_length=200
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(default="cb", help_text="Provider code", max_length=20),
                ),
                (
                    "question_type",
                    models.CharField(
                        db_index=True,
                        default="mcq",
                        help_text="Type of question (mcq, grid_in, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "stimulus",
                    models.TextField(
                        blank=True,
                        help_text="Question context/passage (HTML) - Optional",
                        null=True,
                    ),
                ),
                ("stem", models.TextField(help_text="The actual question text (HTML)")),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Detailed explanation (HTML)"),
                ),
                (
                    "mcq_answer",
                    models.CharField(
                        blank=True, help_text="Correct answer for MCQ (A, B, C, D)", max_length=10
                    ),
                ),
                (
                    "mcq_option_list",
                    models.JSONField(
                        blank=True,
                        help_text="MCQ options as JSON {A: text, B: text, C: text, D: text}",
                        null=True,
                    ),
                ),
                ("tutorial_link", models.URLField(blank=True, help_text="Optional tutorial link")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether question is active for practice",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when question was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when question was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "practice_questions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["identifier_id"], name="practice_qu_identif_a98bf0_idx"),
                    models.Index(fields=["question_id"], name="practice_qu_questio_5e4d19_idx"),
                    models.Index(
                        fields=["domain_code", "skill_code"], name="practice_qu_domain__41c28c_idx"
                    ),
                    models.Index(
                        fields=["domain_code", "is_active"], name="practice_qu_domain__50c2b4_idx"
                    ),
                    models.Index(
                        fields=["skill_code", "is_active"], name="practice_qu_skill_c_901b61_idx"
                    ),
                    models.Index(
                        fields=["question_type", "is_active"], name="practice_qu_questio_fde32e_idx"
                    ),
                ],
            },
        ),
    ]
