# Generated by Django 5.2.8 on 2025-12-01 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique session identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, help_text="Unique session key", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Session status",
                        max_length=20,
                    ),
                ),
                (
                    "domain_code",
                    models.CharField(blank=True, help_text="Filtered domain code", max_length=20),
                ),
                (
                    "skill_code",
                    models.CharField(blank=True, help_text="Filtered skill code", max_length=20),
                ),
                (
                    "provider_code",
                    models.CharField(blank=True, help_text="Filtered provider code", max_length=20),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, help_text="Total questions in this session"),
                ),
                (
                    "questions_answered",
                    models.IntegerField(default=0, help_text="Number of questions answered"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, help_text="Number of correct answers"),
                ),
                (
                    "total_time_seconds",
                    models.IntegerField(default=0, help_text="Total time spent in seconds"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, help_text="When session started"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When session was completed", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last updated timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User taking the practice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Practice Session",
                "verbose_name_plural": "Practice Sessions",
                "db_table": "practice_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_answer",
                    models.CharField(help_text="Answer provided by user", max_length=500),
                ),
                ("correct_answer", models.CharField(help_text="Correct answer", max_length=500)),
                ("is_correct", models.BooleanField(help_text="Whether answer was correct")),
                (
                    "time_taken_seconds",
                    models.IntegerField(default=0, help_text="Time taken to answer in seconds"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the answer was submitted"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question that was answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="practice.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Practice session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="practice.practicesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Answer",
                "verbose_name_plural": "User Answers",
                "db_table": "practice_user_answers",
                "ordering": ["-answered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(fields=["user", "status"], name="practice_se_user_id_c299d8_idx"),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(fields=["session_key"], name="practice_se_session_45dad3_idx"),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(fields=["started_at"], name="practice_se_started_e9b555_idx"),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["session", "question"], name="practice_us_session_7db2e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["user", "is_correct"], name="practice_us_user_id_5ffd00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["answered_at"], name="practice_us_answere_eeedb1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("session", "question")},
        ),
    ]
