# Generated by Django 5.2.8 on 2025-12-01 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_practicesession_useranswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkedQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the question was marked"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question that was marked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marked_by_users",
                        to="practice.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who marked the question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marked_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marked Question",
                "verbose_name_plural": "Marked Questions",
                "db_table": "practice_marked_questions",
                "ordering": ["-marked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "marked_at"], name="practice_ma_user_id_e0eb61_idx"
                    ),
                    models.Index(fields=["question"], name="practice_ma_questio_725a02_idx"),
                ],
                "unique_together": {("user", "question")},
            },
        ),
    ]
