# Generated by Django 5.2.8 on 2025-12-04 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_markedquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasteredQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mastered_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the question was marked as mastered"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question that was mastered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mastered_by_users",
                        to="practice.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who mastered the question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mastered_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mastered Question",
                "verbose_name_plural": "Mastered Questions",
                "db_table": "practice_mastered_questions",
                "ordering": ["-mastered_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "mastered_at"], name="practice_ma_user_id_91128c_idx"
                    ),
                    models.Index(fields=["question"], name="practice_ma_questio_506463_idx"),
                ],
                "unique_together": {("user", "question")},
            },
        ),
    ]
