# Generated by Django 5.2.8 on 2025-12-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_masteredquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="spr_answer",
            field=models.JSONField(
                blank=True,
                help_text="Correct answer(s) for SPR questions as JSON list e.g., ['2.5', '5/2']",
                null=True,
            ),
        ),
    ]
