# Generated by Django 5.2.8 on 2025-12-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_question_spr_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("E", "Easy"), ("M", "Medium"), ("H", "Hard")],
                db_index=True,
                help_text="Question difficulty level (E=Easy, M=Medium, H=Hard)",
                max_length=1,
                null=True,
            ),
        ),
    ]
