# Generated by Django 5.2.8 on 2025-12-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_question_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="current_difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[("E", "Easy"), ("M", "Medium"), ("H", "Hard")],
                help_text="Current difficulty level in adaptive mode",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="practicesession",
            name="is_adaptive",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this is an adaptive practice session",
            ),
        ),
    ]
